### ISSUE TITLE
[Expo][Typescript] Unable to assign children to a styled component

### ISSUE THREAD

**Issue by atanaskanchev** [fedemartinm/fast-styles#16]
**Describe the bug**
Unable to assign children to a styled component.

```tsx
import { defaultTheme, styled } from "@fast-styles/react";
import { View } from "react-native";

export const StyledView = styled(View, {
  flex: 1,
  justifyContent: "center",
  alignItems: "center",
  backgroundColor: "red",
  variants: {
    mode: {
      light: {
        color: defaultTheme.tokens.$textDefault,
      },
      dark: {
        color: defaultTheme.tokens.$textLight,
      },
    },
  },
});
```

```tsx
export default function App() {
  const [mode] = useMode();

  return (
    <ModeProvider>
      <View style={styles.container}>
        <Text>Open up App.tsx to start working on your app!</Text>
        <StyledView mode={mode}>
          <Text>Styled View</Text>
        </StyledView>
        <StatusBar style="auto" />
      </View>
    </ModeProvider>
  );
}
```

```sh
Type 'Element' is not assignable to type 'string | number | OpaqueColorValue | AnimatedNode | Readonly<{ width: number; height: number; }> | (PerpectiveTransform | ... 11 more ... | MatrixTransform)[] | number[] | null | undefined'.ts(2322)
```
<img width="1380" alt="image" src="https://github.com/fedemartinm/fast-styles/assets/4958587/c57bbb3f-a79b-4196-a25f-338849264049">

**To Reproduce**
[Reproducible example](https://github.com/atanaskanchev/fs)

**Expected behavior**
No ts errors

**Environment**
    "@fast-styles/babel-plugin": "^0.2.3",
    "@fast-styles/react": "^0.2.9",
    "expo": "~49.0.8",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4"

**Comment by fedemartinm** [comment]
I believe this error might be related to the issue with useMode #15. 
If you specify the mode manually, you'll see that there's no problem with the children. 

I'll run a few more tests to be sure.

**Comment by atanaskanchev** [comment]
> I believe this error might be related to the issue with useMode #15. If you specify the mode manually, you'll see that there's no problem with the children.
> 
> I'll run a few more tests to be sure.

Thanks for the quick response. You are right, the children error comes from specifying the mode
