### ISSUE TITLE
There's no way to pass a ref to the styled result

### ISSUE THREAD

**Issue by fedemartinm** [fedemartinm/fast-styles#8]
**Quick fix in the tests with**
```js
  // return fast styled component
  return React.forwardRef((props:WithStyles<Props> | VariantsProps<Variants> | StyleProps<Binds>, ref)=>{
    const key = resolveKey(props);
```

**Environment**
 - @fast-styles/react version 0.2.9

**Comment by msantang78** [comment]
@fedemartinm thanks for open sourcing this package, it looks very interesting.
 I just found the same issue while I was giving it a try.  Any reason why is this changes not released?
